name: Proto linter

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }} reg.talenttechlab.org
      - name: Build
        run: docker build -t protocheck .
      - name: Tags
        run: |
          docker tag protocheck reg.talenttechlab.org/public/protocheck:latest
      - name: Push
        run: |
          docker push reg.talenttechlab.org/public/protocheck:latest
