name: Release Package

on:
  push:
#    types:
#      - created

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

#      - name: Prepare
#        run: .bin/prepare_env.sh
#        shell: bash

      - name: Login
        run: docker login -u ${DOCKER_USERNAME} -p "${DOCKER_PASSWORD}" ghcr.io

      - name: Build
        run: docker build -t protocheck .

      - name: Tag
        run: docker tag protocheck ghcr.io/severgroup-tt/protocheck:latest

      - name: Push
        run: docker push ghcr.io/severgroup-tt/protocheck:latest
